### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cyberw** [S1M0N38/har2py#3]
Hi!

I would just like to say thanks for making this! I have taken your code and incorporated in my package locust-plugins (https://github.com/SvenskaSpel/locust-plugins/tree/master/har2locust), modifying it to generate a locust load test instead of a python requests program. I intend to keep improving it to fit my use case.

I have of course kept your license and copyright, I just wanted to say thanks :)

// Lars

**Comment by S1M0N38** [comment]
Thanks. Yeah, I think using jinja2 as template engine makes really easy adding different conversion. Just create a new template (take [requests.jinja2](https://github.com/S1M0N38/har2py/blob/2affff3b2d3872b88dfb14e329e87d6429a565c3/har2py/requests.jinja2) as example) that fits your need.

**Comment by cyberw** [comment]
👍👍
